### ISSUE TITLE
Can not install on Ubuntu

### ISSUE THREAD

**Issue by tredoe** [rsms/tc#3]
Hi,
## I'm using Ubuntu 64; and I installed the libraries and hedaer libraries of TC:
# apt-get install libtokyocabinet3 libtokyocabinet-dev
## but tc can not be installed:

$ python setup.py install  
running install  
running build  
running build_py  
creating build  
creating build/lib.linux-x86_64-2.6  
creating build/lib.linux-x86_64-2.6/tc  
copying lib/tc/release.py -> build/lib.linux-x86_64-2.6/tc  
copying lib/tc/**init**.py -> build/lib.linux-x86_64-2.6/tc  
creating build/lib.linux-x86_64-2.6/tc/test  
copying lib/tc/test/hdb.py -> build/lib.linux-x86_64-2.6/tc/test
copying lib/tc/test/**init**.py -> build/lib.linux-x86_64-2.6/tc/test
copying lib/tc/test/tdb.py -> build/lib.linux-x86_64-2.6/tc/test  
copying lib/tc/test/bdb.py -> build/lib.linux-x86_64-2.6/tc/test  
running build_ext  
running config  
checking for library tokyocabinet  
wrote compile-time configuration to src/system_config.h  
building '_tc' extension  
creating build/temp.linux-x86_64-2.6  
creating build/temp.linux-x86_64-2.6/src  
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wall -Wno-unknown-pragmas -Os -msse3 -fPIC -DPYTC_VERSION="0.7.2" -I/usr/include/python2.6 -c src/__init__.c -o build/temp.linux-x86_64-2.6/src/**init**.o 
src/**init**.c:4:19: error: tcfdb.h: No such file or directory  
src/**init**.c:6:19: error: tctdb.h: No such file or directory  
In file included from src/**init**.c:11:  
src/TDB.h:9: error: expected specifier-qualifier-list before 'TCTDB'  
In file included from src/**init**.c:12:  
src/TDBQuery.h:9: error: expected specifier-qualifier-list before 'TDBQRY'  
src/TDBQuery.h:16: error: expected ')' before '*' token  
src/**init**.c: In function 'init_tc':  
src/**init**.c:116: error: 'HDBTBZIP' undeclared (first use in this function)  
src/**init**.c:116: error: (Each undeclared identifier is reported only once  
src/**init**.c:116: error: for each function it appears in.)  
src/**init**.c:118: error: 'HDBTEXCODEC' undeclared (first use in this function)
src/**init**.c:126: error: 'HDBOTSYNC' undeclared (first use in this function)  
src/**init**.c:134: error: 'BDBTBZIP' undeclared (first use in this function)  
src/**init**.c:136: error: 'BDBTEXCODEC' undeclared (first use in this function)
src/**init**.c:144: error: 'BDBOTSYNC' undeclared (first use in this function)  
src/**init**.c:152: error: 'TDBFOPEN' undeclared (first use in this function)  
src/**init**.c:153: error: 'TDBFFATAL' undeclared (first use in this function)  
src/**init**.c:156: error: 'TDBTLARGE' undeclared (first use in this function)  
src/**init**.c:157: error: 'TDBTDEFLATE' undeclared (first use in this function)
src/**init**.c:158: error: 'TDBTBZIP' undeclared (first use in this function)  
src/**init**.c:159: error: 'TDBTTCBS' undeclared (first use in this function)  
src/**init**.c:160: error: 'TDBTEXCODEC' undeclared (first use in this function)
src/**init**.c:163: error: 'TDBOREADER' undeclared (first use in this function) 
src/**init**.c:164: error: 'TDBOWRITER' undeclared (first use in this function) 
src/**init**.c:165: error: 'TDBOCREAT' undeclared (first use in this function)  
src/**init**.c:166: error: 'TDBOTRUNC' undeclared (first use in this function)  
src/**init**.c:167: error: 'TDBONOLCK' undeclared (first use in this function)  
src/**init**.c:168: error: 'TDBOLCKNB' undeclared (first use in this function)  
src/**init**.c:169: error: 'TDBOTSYNC' undeclared (first use in this function)  
src/**init**.c:172: error: 'TDBITLEXICAL' undeclared (first use in this function)
src/**init**.c:173: error: 'TDBITDECIMAL' undeclared (first use in this function)
src/**init**.c:174: error: 'TDBITOPT' undeclared (first use in this function)
src/**init**.c:175: error: 'TDBITVOID' undeclared (first use in this function)
src/**init**.c:176: error: 'TDBITKEEP' undeclared (first use in this function)
src/**init**.c:179: error: 'TDBQCSTREQ' undeclared (first use in this function)
src/**init**.c:180: error: 'TDBQCSTRINC' undeclared (first use in this function)
src/**init**.c:181: error: 'TDBQCSTRBW' undeclared (first use in this function)
src/**init**.c:182: error: 'TDBQCSTREW' undeclared (first use in this function)
src/**init**.c:183: error: 'TDBQCSTRAND' undeclared (first use in this function)
src/**init**.c:184: error: 'TDBQCSTROR' undeclared (first use in this function)
src/**init**.c:185: error: 'TDBQCSTROREQ' undeclared (first use in this function)
src/**init**.c:186: error: 'TDBQCSTRRX' undeclared (first use in this function)
src/**init**.c:187: error: 'TDBQCNUMEQ' undeclared (first use in this function)
src/**init**.c:188: error: 'TDBQCNUMGT' undeclared (first use in this function)
src/**init**.c:189: error: 'TDBQCNUMGE' undeclared (first use in this function)
src/**init**.c:190: error: 'TDBQCNUMLT' undeclared (first use in this function)
src/**init**.c:191: error: 'TDBQCNUMLE' undeclared (first use in this function)
src/**init**.c:192: error: 'TDBQCNUMBT' undeclared (first use in this function)
src/**init**.c:193: error: 'TDBQCNUMOREQ' undeclared (first use in this function)
src/**init**.c:194: error: 'TDBQCNEGATE' undeclared (first use in this function)
src/**init**.c:195: error: 'TDBQCNOIDX' undeclared (first use in this function)
src/**init**.c:198: error: 'TDBQOSTRASC' undeclared (first use in this function)
src/**init**.c:199: error: 'TDBQOSTRDESC' undeclared (first use in this function)
src/**init**.c:200: error: 'TDBQONUMASC' undeclared (first use in this function)
src/**init**.c:201: error: 'TDBQONUMDESC' undeclared (first use in this function)
src/**init**.c:204: error: 'TDBQPPUT' undeclared (first use in this function)
src/**init**.c:205: error: 'TDBQPOUT' undeclared (first use in this function)
src/**init**.c:206: error: 'TDBQPSTOP' undeclared (first use in this function)

**Comment by russian-developer** [comment]
sudo apt-get install pythonX.X-dev
fix the problem.
