### ISSUE TITLE
TDB has much less Python methods than HDB

### ISSUE THREAD

**Issue by neithere** [rsms/tc#7]
HDB.c defines many useful Python methods for the database object (such as `fsiz`, `iterkeys`, `__getitem__`, `__contains__` and so on), while TDB.c only defines some (7 vs. 33). Is there any real obstacle to include these methods from HDB?

**Comment by rsms** [comment]
The only reason is that the TDB bindings is still under development. You're welcome to make additions and send me a pull req. :)

**Comment by neithere** [comment]
Thanks for your response. I'm not sure I can write any good code in C, but I'll consider that option. ;-)

BTW, I've made a TC backend for [Models](http://pypi.python.org/pypi/models) which depends on tc (and also on some features of [pyrant](http://pypi.python.org/pypi/pyrant)). The TC and TT backends are made in such a way that it is possible to easily swap them without changing the app's code. Of course TDB is required, so it is a bit of a problem that we depend on the development version of tc which is only available from the repo (or not?). Is there any roadmap or the development is conducted under the Scratch The Itch paradigm? :)

**Comment by rsms** [comment]
Checked out models — nice work!

Unfortunately we do not currently use tc much so there is little or no time scheduled for actually do more development at the moment, but I'll look into releasing an update on pypi, macports & debian asap. Most ppl are interested in TDB (incl. myself) so would be a nice addition to a dist.

One question though: Have you used (tested) the current tc (master branch) for long? I.e. is it stable? (As we only use the dist version with H and B I don't know if the current version is stable enough to release). Thanks!

**Comment by neithere** [comment]
I only plan to use TC for real development, and I've experimented mostly with Tyrant, so I'm afraid I didn't have the chance to test tc. However, Models has some basic tests written for the Tyrant backend, and the tc-powered backend passes them as well. Which is no surprise as tc passes its own tests. :)

Some functionality seems to be missing in tc, especially query-related (incl. metasearch), but it has nothing to do with stability, so I would vote for releasing the code.

By the way, [python-tokyocabinet](http://code.google.com/p/python-tokyocabinet/wiki/Tutorial) seems to have more comprehensive TDB support but with a lower-level API. I'll check if it's easier to slap a level of abstraction on top of it instead of improving TDB support in tc; otoh, tc may be improved easier with that code in mind if someone gets around to it...
